export const GET_HOME_SWIPER = 'GET_HOME_SWIPER';

export const GET_HOME_RECOMD_GOODS = 'GET_HOME_RECOMD_GOODS';

export const GET_HOME_GOODS = 'GET_HOME_GOODS';

export const GET_HOME_GOODS_AGAIN = 'GET_HOME_GOODS_AGAIN';